#ifndef MKUI_C_H
#define MKUI_C_H

#pragma once

/* WARNING: This file is auto-generated by cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Status codes returned through [`MkuiResult::code`].
 *
 * Variant names are prefixed with `Mkui` in Rust so cbindgen's
 * ScreamingSnakeCase rename emits them as the v0.4.x-stable
 * `MKUI_SUCCESS` / `MKUI_INVALID_PARAMETER` / … C-header forms.
 */
typedef enum MkuiErrorCode {
  MKUI_SUCCESS = 0,
  MKUI_INITIALIZATION_FAILED = 1,
  MKUI_INVALID_PARAMETER = 2,
  MKUI_RUNTIME_ERROR = 3,
  MKUI_OUT_OF_MEMORY = 4,
} MkuiErrorCode;

/**
 * Opaque app handle. The runtime tree lives inside a `RefCell` so the FFI
 * can mutate it through `*mut MkuiApp` without taking a Rust `&mut` across
 * the boundary.
 */
typedef struct MkuiApp MkuiApp;

/**
 * `repr(C)` mirror of `mkui_runtime::NodeId`. Carries the two `u32`s the
 * runtime uses to detect use-after-free.
 */
typedef struct MkuiNodeId {
  uint32_t index;
  uint32_t generation;
} MkuiNodeId;

/**
 * `repr(C)` mirror of `mkui_runtime::ActionId`.
 */
typedef struct MkuiActionId {
  uint32_t index;
  uint32_t generation;
} MkuiActionId;

typedef struct MkuiResult {
  enum MkuiErrorCode code;
  const char *message;
} MkuiResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const int MKUI_BUTTON_PRIMARY;

extern const int MKUI_BUTTON_SECONDARY;

extern const int MKUI_BUTTON_DESTRUCTIVE;

extern const int MKUI_BUTTON_OUTLINE;

extern const int MKUI_BUTTON_GHOST;

extern const int MKUI_BUTTON_LINK;

extern const int MKUI_TEXT_BODY;

extern const int MKUI_TEXT_HEADING_1;

extern const int MKUI_TEXT_HEADING_2;

extern const int MKUI_TEXT_HEADING_3;

extern const int MKUI_TEXT_CAPTION;

extern const int MKUI_TEXT_LABEL;

extern const int MKUI_TEXT_CODE;

/**
 * Create a new mkui application.
 */
struct MkuiApp *mkui_app_new(void);

/**
 * Free a mkui application.
 */
void mkui_app_free(struct MkuiApp *app);

/**
 * Return the root `NodeId` so the host can attach children to the runtime
 * tree without exposing the synthetic root constant.
 */
struct MkuiNodeId mkui_app_root(const struct MkuiApp *app);

/**
 * Append a `View` under `parent`. Returns the new node's id, or
 * `MkuiNodeId{index=UINT_MAX, generation=UINT_MAX}` on error.
 */
struct MkuiNodeId mkui_app_view_child(struct MkuiApp *app,
                                      struct MkuiNodeId parent,
                                      const char *class_name);

/**
 * Append a `Text` under `parent`.
 */
struct MkuiNodeId mkui_app_text_child(struct MkuiApp *app,
                                      struct MkuiNodeId parent,
                                      const char *content,
                                      int variant,
                                      const char *class_name);

/**
 * Append a `Button` under `parent`. Pass `MkuiActionId{UINT_MAX, UINT_MAX}`
 * for no callback, or an id from [`mkui_app_register_callback`].
 */
struct MkuiNodeId mkui_app_button_child(struct MkuiApp *app,
                                        struct MkuiNodeId parent,
                                        const char *label,
                                        int variant,
                                        const char *class_name,
                                        struct MkuiActionId on_press);

/**
 * Register a C function as a callback. The returned [`MkuiActionId`] is
 * what `mkui_app_button_child` accepts; firing the action invokes
 * `func(user_data)` exactly once.
 *
 * The host is responsible for `user_data` lifetime — mkui never frees it.
 */
struct MkuiActionId mkui_app_register_callback(struct MkuiApp *app,
                                               void (*func)(void*),
                                               void *user_data);

/**
 * Fire a registered callback. Useful for test harnesses; the actual UI
 * fires callbacks via the renderer (console / web / wgpu) when a button
 * is pressed.
 */
struct MkuiResult mkui_app_fire_action(struct MkuiApp *app, struct MkuiActionId id);

/**
 * Run the application via the real console backend. Hands the runtime
 * `AppTree` to `mkui_console::Mkui::from_core` and invokes its interactive
 * loop. The Codex round-8 regression (Sprint 4 round-7 shipped a stub
 * `println!` summary instead of the real backend) is corrected here.
 *
 * Requires the `console` feature (default). Without it, returns
 * `MkuiErrorCode::MkuiRuntimeError`.
 *
 * Single function (not cfg-gated declaration) so cbindgen emits one
 * prototype regardless of build features — duplicate prototypes are
 * invalid C and the header would fail to compile downstream.
 */
struct MkuiResult mkui_app_run_console(struct MkuiApp *app);

/**
 * Emit a canonical JSON snapshot of the current tree. Used by the
 * cross-binding parity tests; the host frees the returned buffer via
 * [`mkui_free_error_message`] (same allocator).
 */
char *mkui_app_snapshot_json(const struct MkuiApp *app);

/**
 * Free an error message or JSON buffer returned by mkui functions.
 */
void mkui_free_error_message(char *message);

/**
 * Get version information.
 */
const char *mkui_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MKUI_C_H */
