//! cbindgen build script — generates `mkui_c.h` from the FFI source.
//!
//! Sprint 4: replaced the prior manual-header bypass with a real
//! `cbindgen::Builder` invocation (audit Phase 2 Task 9 fold-in). The
//! generated header lives at `OUT_DIR/include/mkui_c.h`; the existing
//! handwritten `include/mkui_c.h` is kept as a checked-in reference.
//!
//! cbindgen 0.29.2 clears `atty` + `clap 3` + `bitflags 1` + `syn 1`
//! transitive duplicates from the workspace (3 of 4 advisory ignores
//! pruned in this PR).

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let package_name = env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME");
    let out_dir = target_dir().join("include");
    std::fs::create_dir_all(&out_dir).expect("create include dir");
    let out_file = out_dir.join(format!("{}.h", package_name.replace('-', "_")));

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        pragma_once: true,
        include_guard: Some("MKUI_C_H".into()),
        autogen_warning: Some(
            "/* WARNING: This file is auto-generated by cbindgen. DO NOT EDIT. */".into(),
        ),
        sys_includes: vec!["stdint.h".into(), "stdbool.h".into()],
        export: cbindgen::ExportConfig {
            // Surface every `#[no_mangle]` symbol the FFI re-exports without
            // having to enumerate them by hand (the old cbindgen.toml had a
            // hand-maintained list which drifted when new functions landed).
            ..Default::default()
        },
        ..Default::default()
    };

    let res = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate();

    match res {
        Ok(bindings) => {
            bindings.write_to_file(&out_file);
        }
        Err(e) => {
            // cbindgen can fail on macro expansion in workspace deps. Emit
            // a warning rather than failing the whole build so callers
            // building `mkui-c` for parity tests still get a `cdylib`.
            println!("cargo:warning=cbindgen failed: {e}");
        }
    }

    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=build.rs");
}

fn target_dir() -> PathBuf {
    if let Ok(target) = env::var("CARGO_TARGET_DIR") {
        PathBuf::from(target)
    } else {
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("target")
    }
}
