//! cbindgen build script — generates the public `mkui_c.h` header.
//!
//! Sprint 4 (issue #51) replaced the prior manual-header bypass with a real
//! `cbindgen::Builder` invocation (audit Phase 2 Task 9 fold-in). Codex
//! round-8 P2 follow-up: write to the **checked-in** `include/mkui_c.h`
//! path (not just `target/include/...`) and make cbindgen failure
//! **fatal** — silent header drift between the generated form and the
//! checked-in form is the regression the audit task was meant to close.
//!
//! CI runs `cargo build -p mkui-c` and then verifies
//! `git diff --exit-code crates/mkui-c/include/mkui_c.h` is empty; any
//! drift between the source and the generated form is a build failure.
//!
//! Two opt-outs exist for local-dev ergonomics:
//!   1. `MKUI_C_SKIP_CBINDGEN=1` — skip generation entirely (used when
//!      iterating on Rust code that doesn't change the FFI surface).
//!   2. `DOCS_RS=1` — docs.rs builds without rewriting the source tree
//!      (the build directory is read-only there).

use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=MKUI_C_SKIP_CBINDGEN");
    println!("cargo:rerun-if-env-changed=DOCS_RS");

    if env::var_os("MKUI_C_SKIP_CBINDGEN").is_some() || env::var_os("DOCS_RS").is_some() {
        return;
    }

    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let include_dir = PathBuf::from(&crate_dir).join("include");
    std::fs::create_dir_all(&include_dir).expect("create include dir");
    let out_file = include_dir.join("mkui_c.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        pragma_once: true,
        include_guard: Some("MKUI_C_H".into()),
        autogen_warning: Some(
            "/* WARNING: This file is auto-generated by cbindgen. DO NOT EDIT. */".into(),
        ),
        sys_includes: vec!["stdint.h".into(), "stdbool.h".into(), "stddef.h".into()],
        // Surface every `#[no_mangle]` symbol the FFI re-exports without
        // hand-maintaining the list — the prior `cbindgen.toml`'s
        // explicit `export.include` was the drift vector.
        export: cbindgen::ExportConfig::default(),
        // Rust enum variants are named `MkuiSuccess` / `MkuiInvalidParameter`
        // etc.; cbindgen's ScreamingSnakeCase rename emits them as the
        // v0.4.x-compatible `MKUI_SUCCESS` / `MKUI_INVALID_PARAMETER`
        // forms downstream consumers expect.
        enumeration: cbindgen::EnumConfig {
            rename_variants: cbindgen::RenameRule::ScreamingSnakeCase,
            ..Default::default()
        },
        ..Default::default()
    };

    let bindings = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect(
            "cbindgen failed to generate mkui_c.h — header drift is a build error, \
             not a warning. Fix the FFI source or, if iterating locally on \
             non-FFI code, set MKUI_C_SKIP_CBINDGEN=1 to skip generation.",
        );

    // `write_to_file` only rewrites if the contents differ — keeps mtime
    // stable for incremental builds and `git diff` clean when nothing
    // FFI-shaped changed.
    bindings.write_to_file(&out_file);
}
