[package]
name = "mkui-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true, optional = true }

# Web-specific dependencies
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

# Console-specific dependencies  
ratatui = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde"]
web = ["dep:wasm-bindgen", "dep:web-sys"]
console = ["dep:ratatui"]