[package]
name = "mkui-wgpu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "WGPU-oriented scene primitives and declarative builders for mkui"

[dependencies]
mkui-core = { path = "../mkui-core" }
mkui-text = { path = "../mkui-text" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
